MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/maojunzhu/pycharmprojects/TransReID/weight/jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [11, 11]
  SIE_CAMERA: True
  SIE_COE: 3.0
  JPM: True
  RE_ARRANGE: True

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.0 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5] #[0.485, 0.456, 0.406]
  PIXEL_STD:  [0.5, 0.5, 0.5] #[0.229, 0.224, 0.225]

DATASETS:
  NAMES: ('occ_duke')
  ROOT_DIR: ('/home/maojunzhu/data/duke/Occluded-DukeMTMC-Dataset-master')
#  NAMES: ('market1501')
#  ROOT_DIR: ('/home/maojunzhu/data')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 20
  BASE_LR: 0.0001
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  WARMUP_EPOCHS: 0
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 120
  LOG_PERIOD: 50
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

FINETUNE:
  PRETRAIN_PATH : '/home/maojunzhu/pycharmprojects/TransReID/logs/occ_duke_vit_transreid_stride/transformer_120.pth'
  PRUNE_MODE : 'head_entropy'
  PRUNE_RATE : 0.25
  ITER_NUM : 33
  FINE_NUM : 2
  FINAL_NUM : 150
  DISTILL_TYPE : 'soft'
  DISTILL_ALPHA : 2.0
  DISTILL_TAU : 10

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './logs/occ_duke_transreid_base_head25_150'


